### ISSUE TITLE
QR code Error

### ISSUE THREAD

**Issue by NumbGnat** [jamie-mh/AuthenticatorPro#1052]
**Describe the bug**
I received the following error when attempting to add a new entry, by QR Code, through the camera. 

**To Reproduce**
1. Tap [+] to add new entry.
2. Tap [QR Code]. 
3. Tap [Camera]. 
4. Point camera at QR Code displayed on laptop (or desktop) screen. 

**Expected behavior**
The "Add New Item" dialog should be displayed. 

**App Version**
1.23.0

**Additional context**
The error returned was as follows... 

System.ArgumentException: Handle must be valid. Arg_ParamName_Name, instance
   at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference , JniMethodInfo )
   at Android.Runtime.JNIEnv.CallVoidMethod(IntPtr , IntPtr )
   at AndroidX.Camera.Core.IImageProxyInvoker.Close()
   at AuthenticatorPro.Droid.QrCode.Analyser.MlKitQrCodeImageAnalyser.Analyze(IImageProxy imageProxy)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object )
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
   at Java.Lang.Thread.RunnableImplementor.Run()
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )

**Comment by jamie-mh** [comment]
The MLKit analyser has been removed in 1.24.0. This should no longer occur.
