### ISSUE TITLE
Biometric unlock broken

### ISSUE THREAD

**Issue by technodrome** [jamie-mh/AuthenticatorPro#1150]
**Describe the bug**
Biometric unlock on 1.25.1 does not work. On app startup, I always have to log in using password. When I head to settings and try to enable BU there, modal with fingerprint scan pops up and I can scan my finger. Then the pill button briefly shows BU enabled but then immediately switches back to disabled BU state.

**To Reproduce**
1. Open app, enter password (cannot use BU)
2. Click on Settings, try to enable BU, scan, shows BU enabled for a moment, then switches automatically back to BU disabled

Error `Failed to store cipher` appears in log:
```
1718214892.080 10250 12351 12351 E uthenticatorpr: Invalid ID 0x00000000.
1718214893.317 10250 12351 12351 E AUTHPRO : Failed to store cipher
1718214893.317 10250 12351 12351 E AUTHPRO : System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, s
1718214893.317 10250 12351 12351 E AUTHPRO :    at System.Text.Encoding.GetBytes(String )
1718214893.317 10250 12351 12351 E AUTHPRO :    at System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytes(String )
1718214893.317 10250 12351 12351 E AUTHPRO :    at AuthenticatorPro.Droid.Storage.BiometricStorage.Store(String password, Cipher cipher)
1718214893.317 10250 12351 12351 E AUTHPRO :    at AuthenticatorPro.Droid.Activity.SettingsActivity.<>c__DisplayClass21_0.<EnableBiometrics>b__0(Object _, AuthenticationResult result)
```

**Expected behavior**
Working BU.

**App Version**
1.25.1, Android 11, OnePlus 7Pro

**Additional context**
Full log attached.
[12_06-19-54-39_102.log](https://github.com/user-attachments/files/15809082/12_06-19-54-39_102.log)

**Comment by jamie-mh** [comment]
Hi,

Thanks for the detailed report.
Can you try clearing and setting the app password before enabling biometric unlock?

Cheers

**Comment by technodrome** [comment]
After doing that, the app is completely broken. I cannot even start it, it completely crashes with the following SQLite error which repeats upon every app start.

```
SQLite.SQLiteException: file is not a database
   at SQLite.SQLite3.Prepare2(sqlite3 , String )
   at SQLite.SQLiteCommand.Prepare()
   at SQLite.SQLiteCommand.<ExecuteDeferredQuery>d__121[[SQLite.SQLiteConnection.ColumnInfo, SQLite-net, Version=1.9.172.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Collections.Generic.List1[[SQLite.SQLiteConnection.ColumnInfo, SQLite-net, Version=1.9.172.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable1 )
   at System.Linq.Enumerable.ToList[ColumnInfo](IEnumerable1 )
   at SQLite.SQLiteCommand.ExecuteQuery[ColumnInfo]()
   at SQLite.SQLiteConnection.Query[ColumnInfo](String , Object[] )
   at SQLite.SQLiteConnection.GetTableInfo(String )
   at SQLite.SQLiteConnection.CreateTable(Type , CreateFlags )
   at SQLite.SQLiteConnection.CreateTable[Authenticator](CreateFlags )
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass36_01[[AuthenticatorPro.Core.Entity.Authenticator, AuthenticatorPro.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<CreateTableAsync>b__0(SQLiteConnectionWithLock conn)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass33_01[[SQLite.CreateTableResult, SQLite-net, Version=1.9.172.0, Culture=neutral, PublicKeyToken=null]].<WriteAsync>b__0()
   at System.Threading.Tasks.Task`1[[SQLite.CreateTableResult, SQLite-net, Version=1.9.172.0, Culture=neutral, PublicKeyToken=null]].InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
--- End of stack trace from previous location ---
   at AuthenticatorPro.Droid.Database.MigrateAsync(Boolean firstLaunch)
   at AuthenticatorPro.Droid.Database.OpenAsync(String password, Origin origin)
   at AuthenticatorPro.Droid.Database.OpenAsync(String password, Origin origin)
   at AuthenticatorPro.Droid.Activity.MainActivity.OnResumeAsync()
   at AuthenticatorPro.Droid.Activity.AsyncActivity.OnResume()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncConDisplayClass2_0.<Post>bPost>b__0()
   at Java.Lang.Thread.RunnableImplementor.Run()
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
```

**Comment by technodrome** [comment]
Had to uninstall the app, reinstall and restore from backup. Lost all the settings. Upon fresh install, app works without SQLite issues or biometric unlock. Could be caused by version upgrade but it is definitely not user-friendly or smooth experience. 

@jamie-mh I'll leave it up to you to close this if you do not want to investigate.

**Comment by Uneccessary** [comment]
It works for me using 1.25.1.

OS: One UI 6.0, based of Android 14 (Samsung)

**Comment by theAkito** [comment]
For the sake of helping this issue, I tried it on my Android 11 based custom OS.
Works fine.

However, I just installed this app and didn't add any entries yet. Maybe some older update broke something earlier, which becomes only visible in rare scenarios?

At least, the following strongly suggests, this is the case.

> Upon fresh install, app works without SQLite or biometric unlock issues.

@jamie-mh

Maybe add a warning to an FAQ or the README, so people are aware of such an issue, when upgrading from older versions? 🙂

**Comment by fredkilbourn** [comment]
My biometrics stopped working (I think after my last system update) and I was still on the old Authenticator Pro, I came here and found the new app and restored from backup to the new app and the biometrics continue to not work.  I enable them in settings and they turn back off as soon as I leave the menu.

So, whatever is happening it is affecting both the new and retired app.

Samsung Galaxy S25 Ultra, One UI version 8.0, Android version 16, Play system update Feb 1, 2026, Knox 3.12.

**Comment by jamie-mh** [comment]
Hi @fredkilbourn ,

I have a Galaxy S22 with the same software version as you, no issues.
Is there anything in the debug log that might help? You can check it here : Menu > About > About > Top right (debug icon).

Thanks

**Comment by fredkilbourn** [comment]
> Hi [@fredkilbourn](https://github.com/fredkilbourn) ,
> 
> I have a Galaxy S22 with the same software version as you, no issues. Is there anything in the debug log that might help? You can check it here : Menu > About > About > Top right (debug icon).
> 
> Thanks

immediately after trying to turn on biometrics I went to the debug and this is all that was there:
```
2026-04-11 07:52:18 [ERR] (Stratum.Droid.Activity.SettingsActivity) Failed to get encryption cipher
Java.Lang.RuntimeException: Keystore key generation failed
 ---> Java.Lang.Exception: User authentication required (internal Keystore code: 2 message: system/security/keystore2/src/security_level.rs:762

Caused by:
    0: system/security/keystore2/src/security_level.rs:225
    1: system/security/keystore2/src/security_level.rs:202: Failed to handle super encryption.
    2: system/security/keystore2/src/super_key.rs:695: Device is locked.
    3: Error::Rc(r
```

**Comment by jamie-mh** [comment]
Thanks, the log is rather strange. Have you tried disabling the lock screen on your phone and re-enabling it? It seems like a bug in the Samsung software where the keystore is locked, despite the device being unlocked.

**Comment by fredkilbourn** [comment]
I will try this in a little bit, but I should note it is only this app and the previous version `Authenticator Pro` that have this issue, my biometrics are working on 10s, maybe 100 different other apps.

**Comment by fredkilbourn** [comment]
@jamie-mh It just started working again on it's own...  I noticed biometrics showed up as a grayed out option when I just opened it and was able to enable biometrics in settings.  Flipping the toggle immediately prompted for my fingerprint and after that closing/opening the app prompts for my fingerprint.  No idea why but I'm not going to fuss with it anymore now that it works.
