### ISSUE TITLE
The app crashes when trying to add an account by scanning a QR code

### ISSUE THREAD

**Issue by puka-tchou** [jamie-mh/AuthenticatorPro#1153]
**Describe the bug**
The app crashes when trying to add an account by scanning a QR code.

See error detail below:
```
AuthenticatorPro.ZXing.ZXingException: ImageView parameters are inconsistent (out of bounds)
   at AuthenticatorPro.ZXing.Interop.Guard.ThrowIfNullPointer(IntPtr )
   at AuthenticatorPro.ZXing.ImageView..ctor(Byte[] , Int32 , Int32 , ImageFormat , Int32 , Int32 )
   at AuthenticatorPro.Droid.QrCode.QrCodeImageAnalyser.AnalyseInternal(IImageProxy imageProxy)
   at AuthenticatorPro.Droid.QrCode.QrCodeImageAnalyser.Analyze(IImageProxy imageProxy)
   at AndroidX.Camera.Core.ImageAnalysis.IAnalyzerInvoker.n_Analyze_Landroidx_camera_core_ImageProxy_(IntPtr jnienv, IntPtr native__this, IntPtr native_p0)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
```

**To Reproduce**
1. Click on the "+" icon in the bottom right corner
2. Choose "Scan a QR code"
3. See error

**Expected behavior**
The QR code is correctly scanned.

**App Version**
1.25.1 F-Droid

**Additional context**
N/A

**Comment by puka-tchou** [comment]
It may have been fixed in release `1.25.2` but I can't confirm right now.
