### ISSUE TITLE
Java error everytime I open the app 

### ISSUE THREAD

**Issue by 3ndlos** [jamie-mh/AuthenticatorPro#348]
Hey there, 

today I've added a new QR-Code into the authenticator app. 
Since that the app throws errors everytime I open it. 

I was not able to use the app since that anymore. 
If I go back after the error is shown I'm able to see the codes for 1 second so I could verify that the last added code works as expected and the qr code ist not broken but right now the app is really useless.. 

Hope for assistent - thanks in advance! 

Java.Lang.IllegalArgumentException: me.jmh.authenticatorpro: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00096] in <b6c51311d6954d1caa033cd90930493f>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) <0x7bea456844 + 0x0005f> in <b6c51311d6954d1caa033cd90930493f>:0 
  at Android.App.PendingIntent.GetActivity (Android.Content.Context context, System.Int32 requestCode, Android.Content.Intent intent, Android.App.PendingIntentFlags flags) [0x00081] in <39d349391c6c44cbae8115b49b2a7f6e>:0 
  at AuthenticatorPro.Droid.Worker.AutoBackupWorker.ShowNotification (AuthenticatorPro.Droid.Worker.AutoBackupWorker+NotificationContext context, System.Boolean openAppOnClick, AuthenticatorPro.Shared.Data.Backup.IResult result) [0x00168] in <efc4a642dc614b4b9eb0974cf18092bd>:0 
  at AuthenticatorPro.Droid.Worker.AutoBackupWorker.DoWorkAsync () [0x0030e] in <efc4a642dc614b4b9eb0974cf18092bd>:0 
  at AuthenticatorPro.Droid.Worker.AutoBackupWorker.DoWork () [0x0000c] in <efc4a642dc614b4b9eb0974cf18092bd>:0 
  at AndroidX.Work.Worker.n_DoWork (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <ae0af68784614e55bf14b143131eb3b7>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.78(intptr,intptr)
  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: me.jmh.authenticatorpro: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
	at android.app.PendingIntent.getActivity(PendingIntent.java:451)
	at android.app.PendingIntent.getActivity(PendingIntent.java:415)

**Comment by 3ndlos** [comment]
So I was able to figure our the problem:

Somehow the choosen folder for automatic backups was removed from the app.
I've rechoosen the directory and had also to grant the app access to this folder again?!

Since that the error does not come up anymore so it should be from trying to do a backup and after it failed and you (humen) move back from the error-message the error instant comes up again.

For everybody whos getting the same issue:
Go to settings in the few seconds you have between the error-messages and check your backup settings!

For developer:
Please have a Look into a better solution but anyways thanks for the great App!

**Comment by jamie-mh** [comment]
Hi @3ndlos ,

Thanks for reporting this. Are you running Android 12 on your device?

**Comment by 3ndlos** [comment]
Hey @jamie-mh,

yes a few weeks ago I made an update on my Samsung Galaxy S21+.

**Comment by jamie-mh** [comment]
Fixed in 1.15.6
