### ISSUE TITLE
Exception when accessing settings

### ISSUE THREAD

**Issue by andyman1222** [jamie-mh/AuthenticatorPro#682]
**Describe the bug**
Exception occurred upon accessing settings. The settings window is inaccessible because of this.

```
Java.Security.GeneralSecurityException: Failed to obtain information about key
 ---> Java.Lang.Exception: 112

  --- End of managed Java.Lang.Exception stack trace ---
android.security.KeyStoreException: 112
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1563)
	at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:248)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:368)
	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:120)
	at java.security.KeyStore.getKey(KeyStore.java:1062)
	at crc643c2a2b888a14ec9a.SettingsActivity.n_onCreate(Native Method)
	at crc643c2a2b888a14ec9a.SettingsActivity.onCreate(SettingsActivity.java:45)
	at android.app.Activity.performCreate(Activity.java:7963)
	at android.app.Activity.performCreate(Activity.java:7952)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

  --- End of managed Java.Lang.Exception stack trace ---
android.security.KeyStoreException: 112
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1563)
	at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:248)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:368)
	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:120)
	at java.security.KeyStore.getKey(KeyStore.java:1062)
	at crc643c2a2b888a14ec9a.SettingsActivity.n_onCreate(Native Method)
	at crc643c2a2b888a14ec9a.SettingsActivity.onCreate(SettingsActivity.java:45)
	at android.app.Activity.performCreate(Activity.java:7963)
	at android.app.Activity.performCreate(Activity.java:7952)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

   Exception_EndOfInnerExceptionStack
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualObjectMethod(JniObjectReference , JniObjectReference , JniMethodInfo , JniArgumentValue* )
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualObjectMethod(String , IJavaPeerable , JniArgumentValue* )
   at Java.Security.KeyStore.GetKey(String , Char[] )
   at AuthenticatorPro.Droid.Util.PasswordStorageManager.GetKeyFromKeyStore()
   at AuthenticatorPro.Droid.Util.PasswordStorageManager.GetDecryptionCipher()
   at AuthenticatorPro.Droid.Activity.SettingsActivity.IsBiometricsInvalidated()
   at AuthenticatorPro.Droid.Activity.SettingsActivity.OnCreate(Bundle savedInstanceState)
   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr , IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V , IntPtr , IntPtr , IntPtr )
  --- End of managed Java.Security.GeneralSecurityException stack trace ---
java.security.UnrecoverableKeyException: Failed to obtain information about key
	at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:246)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:368)
	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:120)
	at java.security.KeyStore.getKey(KeyStore.java:1062)
	at crc643c2a2b888a14ec9a.SettingsActivity.n_onCreate(Native Method)
	at crc643c2a2b888a14ec9a.SettingsActivity.onCreate(SettingsActivity.java:45)
	at android.app.Activity.performCreate(Activity.java:7963)
	at android.app.Activity.performCreate(Activity.java:7952)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: android.security.KeyStoreException: 112
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1563)
	at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:248)
	... 20 more

  --- End of managed Java.Security.GeneralSecurityException stack trace ---
java.security.UnrecoverableKeyException: Failed to obtain information about key
	at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:246)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:368)
	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:120)
	at java.security.KeyStore.getKey(KeyStore.java:1062)
	at crc643c2a2b888a14ec9a.SettingsActivity.n_onCreate(Native Method)
	at crc643c2a2b888a14ec9a.SettingsActivity.onCreate(SettingsActivity.java:45)
	at android.app.Activity.performCreate(Activity.java:7963)
	at android.app.Activity.performCreate(Activity.java:7952)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: android.security.KeyStoreException: 112
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1563)
	at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:248)
	... 20 more
```

**To Reproduce**
1. Open app
2. Go to the app settings

Note: this could be caused because of my code configs. I manually imported the codes from a config file of an unsupported app (2fas) and somewhere an error could've occured in the process, though all authentication codes and app password lock still work. I also have the Android wear version of the app set up.

**Expected behavior**
Settings window would open for the app

**App Version**
1.17.2

**Additional context**
See note in "to reproduce"

**Comment by jamie-mh** [comment]
Hi @andyman1222 ,

This seems to be an issue when checking if the biometrics is still active.
Are you able to create a backup, reinstall the app, and restore the backup? This should clear the keystore and fix the error.

When you say you "manually imported the codes", you're saying that you used the import menu, yes ?

Thanks

**Comment by andyman1222** [comment]
A few days ago I went back onto the app and noticed the bug was no longer present. I have auto backups enabled just in case anyways. I can now go into settings and I was able to turn (back) on biometrics. I'm not sure if there was an update that possibly fixed the issue, or it somehow fixed it on its own (like with an auto backup or some biometric setting on my phone changing)

**Comment by jamie-mh** [comment]
Yes, I made a change in the latest update that prevents the crash so that biometrics can be re-enabled.
I'm not sure how you got an `UnrecoverableKeyException` but at least there is now a workaround.
