### ISSUE TITLE
Entering the settings reports an error

### ISSUE THREAD

**Issue by Sunnnight** [jamie-mh/AuthenticatorPro#685]
**Describe the bug**
Click on the settings to report an error

**To Reproduce**
1. Click on 'Settings'
2. See error

**Expected behavior**
Enter the settings page normally

**App Version**
1.17.2

**Additional context**
Java.Security.InvalidKeyException: Only SecretKey is supported
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference , JniObjectReference , JniMethodInfo , JniArgumentValue* )
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
   at Javax.Crypto.Cipher.Init(CipherMode , IKey , IAlgorithmParameterSpec )
   at AuthenticatorPro.Droid.Util.PasswordStorageManager.GetDecryptionCipher()
   at AuthenticatorPro.Droid.Activity.SettingsActivity.IsBiometricsInvalidated()
   at AuthenticatorPro.Droid.Activity.SettingsActivity.OnCreate(Bundle savedInstanceState)
   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr , IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V , IntPtr , IntPtr , IntPtr )
  --- End of managed Java.Security.InvalidKeyException stack trace ---
java.security.InvalidKeyException: Only SecretKey is supported
	at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:473)
	at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:307)
	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2981)
	at javax.crypto.Cipher.tryCombinations(Cipher.java:2892)
	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2797)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:774)
	at javax.crypto.Cipher.init(Cipher.java:1289)
	at javax.crypto.Cipher.init(Cipher.java:1224)
	at crc643c2a2b888a14ec9a.SettingsActivity.n_onCreate(Native Method)
	at crc643c2a2b888a14ec9a.SettingsActivity.onCreate(SettingsActivity.java:45)
	at android.app.Activity.performCreate(Activity.java:8311)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3627)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3783)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7914)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

  --- End of managed Java.Security.InvalidKeyException stack trace ---
java.security.InvalidKeyException: Only SecretKey is supported
	at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:473)
	at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:307)
	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2981)
	at javax.crypto.Cipher.tryCombinations(Cipher.java:2892)
	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2797)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:774)
	at javax.crypto.Cipher.init(Cipher.java:1289)
	at javax.crypto.Cipher.init(Cipher.java:1224)
	at crc643c2a2b888a14ec9a.SettingsActivity.n_onCreate(Native Method)
	at crc643c2a2b888a14ec9a.SettingsActivity.onCreate(SettingsActivity.java:45)
	at android.app.Activity.performCreate(Activity.java:8311)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3627)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3783)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7914)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by jamie-mh** [comment]
Identical to #682
